name: Build and Release

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: debian-11  # 使用较老的 Ubuntu 版本
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up GCC
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc make musl-tools
    
    - name: Build
      run: |
        # 使用 musl-gcc 进行静态链接编译
        musl-gcc -static -O2 zsan-client.c -o zsan_amd64
        strip zsan_amd64
    
    - name: Test binary
      run: |
        ./zsan_amd64 -h || true
        file ./zsan_amd64
        ls -lh ./zsan_amd64
    
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          zsan_amd64
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Upload artifact
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v4
      with:
        name: zsan_amd64
        path: zsan_amd64
        retention-days: 90
